# Generated by Django 5.0.1 on 2024-01-31 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_user_code_user_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
